Transcription errors and editorial changes
standardebooks/jane-austen_northanger-abbey pull request #1
Opened 2023-07-30 23:47 UTC by jennfrye

Mainly these are transcription errors. The few editorial changes I made were a result of correcting those errors.

In the case of changing punctuation and capitalization (especially in my final commit), I expect that many of these are not errors so much as discrepancies, as it seems the Project Gutenberg transcription was based on a different set of source scans than the one SE is using. I didn't do a complete page-by-page comparison; the corrections I did make are those that I identified as possible errors when I was reading through the book, and then I searched the rest of the text for all related errors to make sure the changes are as uniform as possible (for example, I capitalized all cases of "General" that referred to the character, checked the capitalization following each short exclamation, etc.). 

All non-editorial changes I made are consistent with the source scans. 

Additional commits were made to the repository after I initially cloned it—I hope I rebased correctly so that this pull request can be merged. I remember this was a problem for me when I was working on "Villette."

2023-07-31 16:47 UTC, acabal requested changes
Great work, thanks! A few notes to work on before I can merge. Fixing the broken tag, and undoing `chaperon`, can be done by amending those commits instead of creating new commits. For `Pump Room` you can do that in an editorial commit. Thanks!

2023-07-31 16:47 UTC, acabal commented on src/epub/text/chapter-24.xhtml
> -			<p>“Oh! No; she showed me over the greatest part on Saturday⁠—and we were coming here to these rooms⁠—but only”⁠—dropping her voice⁠—“your father was with us.”</p>
Closing `</p>` broken here

2023-07-31 16:47 UTC, acabal commented on src/epub/text/chapter-2.xhtml
> -			<p><abbr>Mrs.</abbr> Allen was one of that numerous class of females, whose society can raise no other emotion than surprise at there being any men in the world who could like them well enough to
Let's leave `chaperone` in all instances as that's the modern spelling

2023-07-31 16:47 UTC, acabal commented on src/epub/text/chapter-27.xhtml
> -				<p>I received your two kind letters with the greatest delight, and have a thousand apologies to make for not answering them sooner. I really am quite ashamed of my idleness; but in this horrid pl
The Pump Room is a historic named place so we should modernize `Pump-room` to `Pump Room`

2023-07-31 16:47 UTC, acabal commented
If you amend the commits don't forget to force push to this PR to update it.

2023-08-01 05:09 UTC, jennfrye commented
Changes made! Thank you for the tips to amend and force push, I would have had a very difficult time figuring that out.

2023-08-01 14:42 UTC, merged

2023-08-01 14:42 UTC, acabal commented
Excellent, thanks!